# Python NumPy Array

## Creating 1 - dimensional NumPy Arrays
The default data type for integer types **int64** and for float types **float64**

In [1]:
# Importing the numpy libary
import numpy as np

# Option 1
# This create an array with 3 elements
a = np.array([1, 3, 5])
print("Option 1 - default:", a)

# Option 2 - (<Start Number>, <End Number>, <Step>)
# This create an array which starts from <Start Number> increment by <Step> and go until <End Number>
# This is an array of 6 elements
a = np.arange(1, 12, 2)
print("Option 2 - arange:", a)

# Option 3 - (<End Number>)
# This create an array which starts from 0 increment by 1 and go until <End Number>
# This is an array of 10 elements
a = np.arange(10)
print("Option 3 - arange:", a)

# Option 4 - (<Start Number>, <End Number>, <Number of elements including Start and End Number>)
# This creates a floting type array with 6 elements
a = np.linspace(1, 12, 6)
print("Option 4 - linspace:", a)

# Option 5 - (<Number of Elements>)
# This creates an empty array where each element has initialized to float type zero (0.)
# This is an array of 3 elements
z = np.zeros(3)
print("Option 5 - zeros:", z)

# Option 6 - (<Number of Elements>)
# This creates an array where each element has initialized to float type one (1.)
# This is an array of 3 elements
z = np.ones(3)
print("Option 6 - ones:", z)

# Option 7 - (<Number of Elements>, <Initialization Value>)
# This creates an array where each element can initialize to specific number
# This is an array of 3 elements
z = np.full(3, 99)
print("Option 7 - full:", z)

# Option 8 - (<Number of Elements>)
# This creates a float type array with random values which ranges from 0 to 1
# This is an array of 5 elements
z = np.random.random(5)
print("Option 8 - random:", z)

# Option 9 - (<Number of Elements>)
# This creates a float type array with random values which ranges from 0 to 1
# This is an array of 5 elements
z = np.random.rand(5)
print("Option 9 - rand:", z)

# Option 10 - (<Start Number>, <End Number>, <Number of elements including Start and End Number>)
# This creates an integer type array with 5 elements
z = np.random.randint(0, 10, 5)
print("Option 10 - randint:", z)

Option 1 - default: [1 3 5]
Option 2 - arange: [ 1  3  5  7  9 11]
Option 3 - arange: [0 1 2 3 4 5 6 7 8 9]
Option 4 - linspace: [ 1.   3.2  5.4  7.6  9.8 12. ]
Option 5 - zeros: [0. 0. 0.]
Option 6 - ones: [1. 1. 1.]
Option 7 - full: [99 99 99]
Option 8 - random: [0.89495195 0.10101941 0.92948127 0.20770333 0.39370764]
Option 9 - rand: [0.86292283 0.79458739 0.7488586  0.47798346 0.68828358]
Option 10 - randint: [0 3 8 3 3]


In [2]:
# Change the default data type to customer data type
# Following change default int64 type to int16 at the time of array creation
n = np.array([1, 3, 5], dtype = np.int16 )
print('Array Value:', n)
print("Array Type:", n.dtype)
print('Array Element Memory Usage:', n.itemsize, "bytes")
print('Array Memory Usage:', n.itemsize * n.size, "bytes")

Array Value: [1 3 5]
Array Type: int16
Array Element Memory Usage: 2 bytes
Array Memory Usage: 6 bytes


In [3]:
print("Previous:", a)
# Reshape the 1D array into 2D array (like a table)
# (<Row Count>, <Column Count>)
a = a.reshape(3, 2)
a

Previous: [ 1.   3.2  5.4  7.6  9.8 12. ]


array([[ 1. ,  3.2],
       [ 5.4,  7.6],
       [ 9.8, 12. ]])

### Properties of an array object

In [4]:
# Get the size of the array regardless of the shape
size = a.size
print('Array Size:', size)

# Get the shape of the array
shape = a.shape
print('Array Shape:', shape)

# Get the data type of each element of the array
data_type = a.dtype
print('Array Type:', data_type)

# Get how much memory each element has been allocated in the array
item_size = a.itemsize
print("Array Element Memory Usage:", item_size, "bytes") 

# Get total memory allocation for the array
total_mem = item_size * size
print("Array Total Memory consumption:", total_mem, "bytes")

# Get array dimension
dim = a.ndim
print("Array Dimension:", dim)

Array Size: 6
Array Shape: (3, 2)
Array Type: float64
Array Element Memory Usage: 8 bytes
Array Total Memory consumption: 48 bytes
Array Dimension: 2


## Creating 2 - dimensional NumPy Arrays

In [5]:
# Option 1
# Creates an array with 2 rows and 3 columns
# NOTE: Use of parentheses
b = np.array([(1.5, 2, 3), (4, 5, 6)])
print("Option 1:\n", b)

# Option 2
# Creates an array with 2 rows and 3 columns
# NOTE: Use of Square brackets
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print("Option 2:\n", b)
              
# Option 3 - (<Row Count>, <Column Count>)
# This creates an empty array where each element has initialized to float type zero (0.)
# NOTE: use parentheses multiple times
z = np.zeros((3, 4))
print("Oprion 3:\n", z)

# Option 4 - (<Row Count>, <Column Count>)
# This creates an array where each element has initialized to float type one (1.)
# NOTE: use parentheses multiple times
z = np.ones((3, 4))
print("Option 4:\n", z)

# Option 5 - (<Row Count>, <Column Count>)
# This creates an array with random values which ranges from 0 to 1 (float type)
# NOTE: use parentheses multiple times
z = np.random.random((3, 4))
print("Option 5:\n", z)

# Option 6 - (<Row Count>, <Column Count>)
# This creates an array with random values which ranges from 0 to 1 (float type)
# NOTE: No additional parentheses as in random function
z = np.random.rand(3, 4)
print("Option 6:\n", z)

# Option 7 - (<Upper Bound for Random Values - Exclusive>, <Shape of the Array>)
# This creates an array with random values which ranges from 0 to 6 (int type)
z = np.random.randint(7, size=(3,3))
print("Option 7:\n", z)

# Option 8 - (<Low Bound - Inclusive>, <Upper Bound - Inclusive>, <Shape of the Array>)
# This creates an array with random values which ranges from 2 to 9 (int type)
z = np.random.randint(1, 10, size=(4, 4))
print("Option 8:\n", z)

Option 1:
 [[1.5 2.  3. ]
 [4.  5.  6. ]]
Option 2:
 [[9. 8. 7.]
 [6. 5. 4.]]
Oprion 3:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Option 4:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Option 5:
 [[0.48896977 0.03132083 0.88719951 0.95934799]
 [0.53657532 0.77846268 0.11104192 0.12812323]
 [0.36033813 0.87592147 0.62941077 0.02252625]]
Option 6:
 [[0.73701939 0.39414836 0.24388503 0.2291038 ]
 [0.85634743 0.33048433 0.58424838 0.44528493]
 [0.97201899 0.03327451 0.60576979 0.28641703]]
Option 7:
 [[6 2 2]
 [0 2 5]
 [5 0 4]]
Option 8:
 [[6 3 7 2]
 [2 6 9 6]
 [9 5 3 1]
 [4 6 6 3]]


## Matrix

In [6]:
# Identity Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Array Operations
### Comparison
Compare each element of the array.
Following checks whether each element of the array is less than 4

In [7]:
compare = a < 4
compare

array([[ True,  True],
       [False, False],
       [False, False]])

### Arithmatic Operations

In [8]:
# Create a new array
a = np.array([1, 2, 3, 4])
print("Array a:", a)

# Element wise addition
add = a +2
print("Add 2:", add)

# Element wise subtraction
sub = a - 2
print("Subtract by 2:", sub)

# Element wise multiplication
mult = a * 2
print("Multiply by 2:", mult)

# Element wise division
div = a / 2
print("Divide by 2:", div)

# Element wise power
pow = a ** 2
print("Powered by 2:", pow)


# Another array
b = np.array([1, 0, 1, 0])
print("Array b:", b)

# Add two arrays
add = a + b
print("Two arrays addition:", add)

Array a: [1 2 3 4]
Add 2: [3 4 5 6]
Subtract by 2: [-1  0  1  2]
Multiply by 2: [2 4 6 8]
Divide by 2: [0.5 1.  1.5 2. ]
Powered by 2: [ 1  4  9 16]
Array b: [1 0 1 0]
Two arrays addition: [2 2 4 4]


### Repeat array

In [9]:
# New 1D array with 3 elements
arr = np.array([1, 2, 3])

# Repeat each element 3 times
r = np.repeat(arr, 3) 
# OR 
# r = np.repeat(arr, 3, axis=0)
print("1D Array:", r)

# New 2D 1 x 3 array
arr = np.array([[1, 2, 3]])

# Repeat each row 3 times 
r = np.repeat(arr, 3, axis = 0)
print("2D Array, Repeat Row:\n", r)

# Repeat each column 3 times
r = np.repeat(arr, 3, axis = 1)
print("2D Array, Repeat Column:\n", r)


1D Array: [1 1 1 2 2 2 3 3 3]
2D Array, Repeat Row:
 [[1 2 3]
 [1 2 3]
 [1 2 3]]
2D Array, Repeat Column:
 [[1 1 1 2 2 2 3 3 3]]


### Array Copy

In [10]:
# Create a new array
org = np.array([1, 2, 3])

# Copy the created array to new variable
# It copies the content of the element rather than the reference
cop = org.copy()

# Update the cop array
cop[1] = 444

print("Original Array:", org)
print("Copied Array:", cop)

Original Array: [1 2 3]
Copied Array: [  1 444   3]


## Statistical Opeations

### With 1 - dimensional Arrays

In [11]:
# New Array
a = np.random.randint(1, 10, 5)
print("Array:", a)

# Sum
sm = a.sum()
print("Sum Of Array:", sm)

# Min
mi = a.min()
print("Minimum Value of Array:", mi)

# Max
mx = a.max()
print("Maximum Value of Array:", mx)

# Mean or Average
me = a.mean()
print("Mean Value of Array:", me)

# Variance
va = a.var()
print("Variance of Array:", va)

# Standard Deviation
sd = a.std()
print("Standard Deviation of Array:", sd)

Array: [8 8 1 3 9]
Sum Of Array: 29
Minimum Value of Array: 1
Maximum Value of Array: 9
Mean Value of Array: 5.8
Variance of Array: 10.16
Standard Deviation of Array: 3.1874754901018454


### With 2 - dimensional Arrays

In [12]:
# New Array with 6 element
a = np.random.randint(1, 10, 6)
print("1D Array:", a)

# Reshape the array for 3 rows and 2 columns
a = a.reshape(3, 2)
print("2D Array:\n", a)

# Sum
# axis=None means all the elements in the array (defautl) 
# axis = 0 means along the column
# axis = 1 means working along the row.
smc = a.sum(axis = 0)
print("Sum Along the Array Columns:\n", smc)
smr = a.sum(axis = 1)
print("Sum Along the Array Rows:\n", smr)

1D Array: [4 6 8 8 6 6]
2D Array:
 [[4 6]
 [8 8]
 [6 6]]
Sum Along the Array Columns:
 [18 20]
Sum Along the Array Rows:
 [10 16 12]


## Random Operations

In [13]:
# New array
a = np.arange(10)
print("Array:", a)

# Shuffle the array randomly
np.random.shuffle(a)
print("Array after shuffle:", a)

# Chose a random value for the array
num = np.random.choice(a)
print("Randomly selected valye:", num)

Array: [0 1 2 3 4 5 6 7 8 9]
Array after shuffle: [1 6 0 9 2 5 7 4 8 3]
Randomly selected valye: 4


## Accessing Elements

Numpy creates zero index arrays.

In [14]:
# New 3 x 7 array
x = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14], [15, 16, 17, 18, 19, 20, 21]])
print(x)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


![3 By 7 Array](array_3_by_7.png)

In [15]:
# Get a specific element - 13
# Format - [<Row Index>, <Column Index>]
print("Option 1:", x[1, 5])

# OR
print("Option 2:", x[1, -2])

Option 1: 13
Option 2: 13


In [16]:
# Get a specific Row - 2nd row
# Format - [<Row Index>, :]
print("Second Row:", x[1, :])

# Get a specific column - 3rd column
# Format - [ : , <Column Index>]
print("Third Column:", x[: , 2])

Second Row: [ 8  9 10 11 12 13 14]
Third Column: [ 3 10 17]


In [17]:
# Getting a specific row, specific columns - 2nd row and 1st, 2nd, 3rd columns
# Format - [<Row Index>, <Start Column Index (Inclusive)> : <End Column Index (Exclusive)>]
x[1, 1:4]

array([ 9, 10, 11])

In [18]:
# Getting a specific column, specific rows - 3rd column, 1st and 2nd rows
# Format - [<Start Row Index (Inclusive)> : <End Row Index (Exclusive)>, <Column Index>]
x[0:2, 2]

array([ 3, 10])

In [19]:
# Getting a specific row, specific columns with an interval - 3rd row and 2nd, 4th, 6th columns
# Format - [<Row Index>, <Start Column Index (Inclusive)> : <End Column Index (Exclusive)> : <Step Size>]
x[2, 1:6:2]

array([16, 18, 20])

## Modifying Elements

In [20]:
# Change an element at 2nd row, 6th column to 100
x[1,5] = 100
x

array([[  1,   2,   3,   4,   5,   6,   7],
       [  8,   9,  10,  11,  12, 100,  14],
       [ 15,  16,  17,  18,  19,  20,  21]])

In [21]:
# Change an entire column by specific value - 3rd column by 200
x[:, 2] = 200
x

array([[  1,   2, 200,   4,   5,   6,   7],
       [  8,   9, 200,  11,  12, 100,  14],
       [ 15,  16, 200,  18,  19,  20,  21]])

In [22]:
# OR
# Change the entire column by specific list of values - 2nd column by [300, 400, 500]
x[:, 1] = [300, 400, 500]
x

array([[  1, 300, 200,   4,   5,   6,   7],
       [  8, 400, 200,  11,  12, 100,  14],
       [ 15, 500, 200,  18,  19,  20,  21]])

In [23]:
# Change an entire row by specific value - 1st row by 600
x[0, :] = 600
x

array([[600, 600, 600, 600, 600, 600, 600],
       [  8, 400, 200,  11,  12, 100,  14],
       [ 15, 500, 200,  18,  19,  20,  21]])

In [24]:
# Change specific set of columns in a row by specific value - In 2nd row, last 3 columns by 700
x[1, 4:7] = 700
x

array([[600, 600, 600, 600, 600, 600, 600],
       [  8, 400, 200,  11, 700, 700, 700],
       [ 15, 500, 200,  18,  19,  20,  21]])

## 3 dimensional example

In [25]:
b = np.array([
    [[1, 2], 
     [3, 4]], 
    [[5, 6], 
     [7, 8]]
])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [26]:
# Get specific element
# Format - [<Row Index>, <Column Index>, <Depth Index>]
b[0, 1, 1]

4

In [27]:
# Update specific element
b[0, 1, 1] = 20
b

array([[[ 1,  2],
        [ 3, 20]],

       [[ 5,  6],
        [ 7,  8]]])

## Loading Data From a File

In [36]:
# Loads data from a text file
filedata = np.genfromtxt("data.txt", delimiter=",")
print("Float Type:\n", filedata)

# Since the default data type is float, change the element types into int
filedata = filedata.astype("int32")
print("Integer Type:\n", filedata)


Float Type:
 [[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
Integer Type:
 [[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


## Boolean Masking and Advance Indexing

In [37]:
# Check which element values are greater than 50
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [41]:
# Get elements greater than 50
gt_50 = filedata[filedata > 50]
print("Greater Than 50:\n", gt_50)

# Index with a list in Numpy
index_list = [1, 3, 5, 7]
x = gt_50[index_list]
print("Selected Index Elements:\n", x)

Greater Than 50:
 [196  75 766  75  55 999  78  76  88]
Selected Index Elements:
 [ 75  75 999  76]


### np.any()

In [46]:
print("File Data:\n", filedata)

# Find in which columns have values greater than 50 (not considering all the values in the column)
columns_gt_50 = np.any(filedata > 50, axis=0)
print("Columns Greater Than 50:\n", columns_gt_50)

# Find in which rows have values greater than 50 (not considering all the values in the row)
rows_gt_50 = np.any(filedata > 50, axis=1)
print("Rows Greater Than 50:\n", rows_gt_50)

File Data:
 [[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
Columns Greater Than 50:
 [False False False False  True  True False  True  True False False False
 False False False False  True  True]
Rows Greater Than 50:
 [ True  True  True]


### np.all()

In [49]:
# Find in which columns have all the values greater than 50 (considering all the values in the column)
x = np.all(filedata > 50, axis=0)
print("Columns Greater Than 50:\n", x)

# Find in which rows have all the values greater than 50 (considering all the values in the row)
y = np.all(filedata > 50, axis=1)
print("Rows Greater Than 50:\n", y)

Columns Greater Than 50:
 [False False False False  True False False False False False False False
 False False False False False False]
Rows Greater Than 50:
 [False False False]


In [50]:
# Get values greater than 50 and less than 100
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [52]:
# Get values not greater than 50 and not less than 100 (Opposite of previous)
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])

## Exercise 1

Generate following 2D array
```
[1, 1, 1, 1, 1]
[1, 0, 0, 0, 1]
[1, 0, 9, 0, 1]
[1, 0, 0, 0, 1]
[1, 1, 1, 1, 1]
```

In [28]:
# Create a 5 x 5 array initialized to 1
result = np.ones([5, 5], dtype="int32")
print("5 x 5 Array with ones:\n",result)

# Create a 3 x 3 array initialized to 0
middle = np.zeros((3, 3), dtype = "int32")
print("3 x 3 Array with zeros:\n", middle)

# Update the middle element of 3 x 3 array from 9
middle[1,1] = 9
print("3 x 3 Array with 9 middle:\n", middle)

# Update the result 5 x 5 array using 3 x 3 array
result[1:4, 1:4] = middle
print("Final Result:\n", result)

5 x 5 Array with ones:
 [[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
3 x 3 Array with zeros:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
3 x 3 Array with 9 middle:
 [[0 0 0]
 [0 9 0]
 [0 0 0]]
Final Result:
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


## Exercise 2

![Sample Matrix](exercise_2.png)

In [59]:
exe_2 = np.arange(30) + 1
exe_2 = exe_2.reshape((6, 5))
print(exe_2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [60]:
# Q1
exe_2[2:4, :2]

array([[11, 12],
       [16, 17]])

In [61]:
# Q2
exe_2[[0, 1, 2, 3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [ ]:
# Q3
exe_2[[0, 4, 5], ]